### ISSUE TITLE
Events and Data structure

### ISSUE THREAD

**Issue by LukeHankey** [Vthechamp22/kindly-kappa#25]
# Events
For both the backend and frontend, we should develop an event handler. When receiving requests, the json data will have a type key, identifying the event.

C2S = Client to Server

I think we have agreed on:
- Connect (C2S)
- Disconnect (C2S)
- Sync (Both)
- Replace (Both)
- Insert (Both)
- Remove (Both)

The frontend will send connect and disconnect event types. 

Sync would be for when a new connection joins an existing room and maybe periodically sent from the backend to keep all clients up to date with the latest changes.

Both frontend and backend will send sync (above), replace, insert and remove events. Insert and remove events will mostly be from frontend to backend to update the backend cache of the real-time typing. Depending on the code modifiers, these will also be sent from backend to frontend. Replace seems likely that it will just be backend to frontend unless we are able to check if the client has deleted an entire line of code.

# Data Structure

This is just a mock and is likely to change with additional data, key changes, data structure changes, etc. I just wanted to make this issue so we can all input and agree on a particular data structure so we can continue development

# Tasks

- [x] Create a consistent interface for sending and receiving data (#31)
- [x] C2S events update server cache for a room instance (#36)
- [x] Difficulty sent on initial connect only ([Features can be added later](https://github.com/Vthechamp22/kindly-kappa/issues/25#issuecomment-1193312739)) (#32)
- [x] Errors (#28)
- [x] Username support (#17) + ID management
- [ ] Cursor movement
- [x] Room code generated by client ([c69c592](https://github.com/Vthechamp22/kindly-kappa/pull/26/commits/c69c59264480e0f513a31dc50b0101b793f90d77))

**Comment by bensgilbert** [comment]
We also need an Error type when, for instance, the room code that the client specifies is invalid.

**Comment by LukeHankey** [comment]
> We also need an Error type when, for instance, the room code that the client specifies is invalid.

Sounds good. This would be a type, status and data.message?

**Comment by LukeHankey** [comment]
For the difficulty:
- Are we sending it on initial request only?
- Do we give the option to increase / decrease difficulty during the game?
- When a new user joins an existing room, are we modifying the difficulty?

**Comment by bensgilbert** [comment]
Sending the difficulty and room code is probably best to do **only** in the initial message from the client (when creating/joining a room). If the client is joining the room then they should expect the difficulty to be sent back from the server.

I think the ability to modify the difficulty mid-game is an important feature. We could piggyback off of the `sync` event type but since that's more used for syncing the client and server code, I'd recommend making a new event type: `control` which also encompasses the error type stated above.

I don't think it should be done automatically since it might be a bit unexpected, the user should be given the change the difficulty throughout so if their friends join then they can manually edit it to their liking however it might be nice to ask the user when a new collaborator joins if they want to change the difficulty.

**Comment by LukeHankey** [comment]
> Sending the difficulty and room code is probably best to do only in the initial message from the client (when creating/joining a room).

```py
@app.websocket("/room/{room_name}")
async def room(websocket: WebSocket, room_name: str) -> None:
```
We currently receive the room_name from when a client connects to a room (new or existing). I guess we could receive the difficulty on initial connect and cache that.

> I think the ability to modify the difficulty mid-game is an important feature. We could piggyback off of the sync event type but since that's more used for syncing the client and server code, I'd recommend making a new event type: control which also encompasses the error type stated above.

The `control` as in game control, or something else? What errors would be expected here? I can understand the error for connecting to an invalid room, but given this, what would be deemed as invalid? Would there need to be validation or would the invalid name just be from trying to join a game that doesn't exist?

> I don't think it should be done automatically since it might be a bit unexpected, the user should be given the change the difficulty throughout so if their friends join then they can manually edit it to their liking however it might be nice to ask the user when a new collaborator joins if they want to change the difficulty.

This sounds good. Perhaps we could have some other options when creating a room:
- Scale difficulty as time goes on
- Increase difficulty upon a new user joining

All these would be extra features once we have a MVP though.

**Comment by bensgilbert** [comment]
If the client wants to create a room where does their websocket connect? Leaving the room code generation to the client could lead to naming collisions whereas the server generating a 4 digit code (for example) could eliminate this.

**Comment by bensgilbert** [comment]
> The control as in game control, or something else? What errors would be expected here? I can understand the error for connecting to an invalid room, but given this, what would be deemed as invalid? Would there need to be validation or would the invalid name just be from trying to join a game that doesn't exist?

It would almost be like a meta event, providing information about the game rather then actively contributing towards it. It could be used for errors (like the missing room where an error is generated if the client specifies a room that doesn't currently exist, no need for validation since if its not "valid" then it wont exist) and changing settings such as the difficulty mid-game.

**Comment by LukeHankey** [comment]
> If the client wants to create a room where does their websocket connect? Leaving the room code generation to the client could lead to naming collisions whereas the server generating a 4 digit code (for example) could eliminate this.

Creating or joining a room would use the same websocket route in the above post where they only need to provide a name for the room. Joining would check the list of rooms to see if that room name is already created.

**Comment by LukeHankey** [comment]
> > The control as in game control, or something else? What errors would be expected here? I can understand the error for connecting to an invalid room, but given this, what would be deemed as invalid? Would there need to be validation or would the invalid name just be from trying to join a game that doesn't exist?
> 
> It would almost be like a meta event, providing information about the game rather then actively contributing towards it. It could be used for errors (like the missing room where an error is generated if the client specifies a room that doesn't currently exist, no need for validation since if its not "valid" then it wont exist) and changing settings such as the difficulty mid-game.

I guess when the backend receives a connect event (for an existing game) and checks for the room_name, we could send back that `control` event or send ~a disconnect with~ the error directly as:

```json
{
    "type": str,
    "data": {
        "message": str,
    },
    "status": int
}
```

**Comment by LukeHankey** [comment]
Updated Client to Server. This seems correct, right? The client should be sending random lines of code to modify over time.
```json
{
    "type": str,
    "data": {
        "message": str,
        "difficulty": int
        "code": [
            {
                "line_number": int,
                "value": str
            }
        ]
    },
}
```

**Comment by bensgilbert** [comment]
The client shouldn't be sending any lines of code to the server? The server has a record of the rooms code which it uses to generated the modified code.
The only thing that the client sends to the server is the connecting events and the events that update the servers code cache.

**Comment by LukeHankey** [comment]
> The client shouldn't be sending any lines of code to the server? The server has a record of the rooms code which it uses to generated the modified code. The only thing that the client sends to the server is the connecting events and the events that update the servers code cache.

Updating the servers code cache would be sending code to the server, no?

I'm not sure what you mean by the second sentence. If no code is being sent from the client, how does the server know what code to modify and send back?

**Comment by bensgilbert** [comment]
I meant the client sends updates per character as they type, not whole lines of code at once. For example, if I typed the "a" character, the client would send "a" to the server. This allows live typing as seen in google docs etc.

**Comment by LukeHankey** [comment]
> I meant the client sends updates per character as they type, not whole lines of code at once. For example, if I typed the "a" character, the client would send "a" to the server. This allows live typing as seen in google docs etc.

Makes a lot more sense 😆 

Would the client also need to send what type of transformation is done as well? For example, an addition of 'a' or removing 'a' to account for adding code and modifying code.

**Comment by kappq** [comment]
> Would the client also need to send what type of transformation is done as well? For example, an addition of 'a' or removing 'a' to account for adding code and modifying code.

Yup, they would be the `insert` and `remove` types.

**Comment by bensgilbert** [comment]
Note: since both the frontend and backend implementations use an array to store the lines, its easier for every location in code to be represented by a line and column number.

for example: when the client presses the "a" key, something like this could be sent:
```json
{
    "type": "insert",
    "data": {
        "value": "a",
        "location": {
            "line": 5,
            "col": 16
        }
    }
}
```

**Comment by LukeHankey** [comment]
Would it be easier on the frontend to just sent an object for single values or be consistent and use arrays?

**Comment by bensgilbert** [comment]
what do you mean? can you provide an example.

**Comment by LukeHankey** [comment]
So you used:
```json
{
    "type": "insert",
    "data": {
        "value": "a",
        "location": {
            "line": 5,
            "col": 16
        }
    }
}
```
But say if the backend were to send a replace, it might be best to send an array of changes:
```json
{
    "type": "replace",
    "data": {
        "message": "replaces code",
        "code": [
            {
                "value": "def say_hello()\n",
                "location": {
                    "line": 3
                }
            },
            {
                "value": "  return 'Hello\n'",
                "location": {
                    "line": 4
                }
            }
        ]
    }
}
```

**Comment by bensgilbert** [comment]
Good point, we should use an array.

**Comment by LukeHankey** [comment]
I'll write up an example of each and add to the first post

**Comment by bensgilbert** [comment]
Suggestion:

Connect (C2S)
**Sent by the client when joining a room** - a `roomcode` attribute must be present, if a room already exists with the same room code then the client connects to that room, if a room doesn't already exist then a room is created with that room code. A `username` must also exist to identify the user along with a random 4 character `id` to distinguish between users with identical names.
**Sent by the server when another client joins the room** - this contains the `username` of the joined user

example 1: client -> server (the user is connecting to a room):
```json
{
    "type": "connect",
    "data": {
        "username": "Evorage",
        "id": "OGNF",
        "roomcode": "AYGH"
    }
}
```
example 2: server -> client (another user connected so the server updates the original user):
```json
{
    "type": "connect",
    "data": {
        "username": "Luke",
        "id": "PFNE"
    }
}
```

**Comment by LukeHankey** [comment]
> Connect (C2S) **Sent by the client when joining a room** - a `roomcode` attribute must be present, if a room already exists with the same room code then the client connects to that room, if a room doesn't already exist then a room is created with that room code. A `username` must also exist to identify the user along with a random 4 character `id` to distinguish between users with identical names. **Sent by the server when another client joins the room** - this contains the `username` of the joined user
> 
> example 1: client -> server (the user is connecting to a room):
> 
> ```json
> {
>     "type": "connect",
>     "data": {
>         "username": "Evorage",
>         "id": "OGNF",
>         "roomcode": "AYGH"
>     }
> }
> ```
> 
> example 2: server -> client (another user connected so the server updates the original user):
> 
> ```json
> {
>     "type": "connect",
>     "data": {
>         "username": "Luke",
>         "id": "PFNE"
>     }
> }
> ```

A username would be good (#17) as the visible identifier. The id is generated via the backend with UUID, so that doesn't need to be generated on the frontend as we use the id for hashing.

 > if a room doesn't already exist then a room is created with that room code
Would we not sent an error back instead since we have the two buttons, one for joining and one for creating a new room?

The roomcode doesn't need to be sent in the json data as that will be provided from the ws URL and the username can also be captured as a query parameter, identified in #17. 

What do you mean by another client connecting to the same room will update the original user?

--
Have provided examples in OP.

**Comment by bensgilbert** [comment]
> A username would be good (https://github.com/Vthechamp22/kindly-kappa/issues/17) as the visible identifier. The id is generated via the backend with UUID, so that doesn't need to be generated on the frontend as we use the id for hashing.

Can the backend send the ID in the `connect` event to the other clients, I see your point that the frontend doesn't need to generate one and since each client doesn't need to know their own ID, the `connect` event would be perfect. It's to allow people with the same username to be in the same room, it's either that or they are forced to change their username.

> The roomcode doesn't need to be sent in the json data as that will be provided from the ws URL and the username can also be captured as a query parameter, identified in https://github.com/Vthechamp22/kindly-kappa/issues/17.

Ahh, I've got it now :)

> What do you mean by another client connecting to the same room will update the original user?

As in, if client A is connect to a room and client B joins, then the server needs to update client A (the original user) with a `connect` event. I phrased it badly.

**Comment by LukeHankey** [comment]
Possible errors:
- Joining a game without an active room (InvalidCode)

How do we want to handle the room owner leaving the game but client B still in the game? Do we:
- Transfer ownership so the room now becomes Client B's room
- Disconnect client B and send an error (HostLeftGame (?))

**Comment by bensgilbert** [comment]
Process for connecting clients:
Imagine there exists a room with a single client (client A).
Client B joins and receives a `sync` event from the server containing the rooms current code and collaborators
Client A (and anyone else potentially in the room) receives a `connect` event which allows them to update their local cache of the collaborators.

**Comment by bensgilbert** [comment]
> How do we want to handle the room owner leaving the game but client B still in the game? Do we:
Transfer ownership so the room now becomes Client B's room
Disconnect client B and send an error (HostLeftGame (?))

I prefer the first option since it allows for dropped connections etc. What do you think? When all the collaborators have left the room, **then** it should be deleted right?

**Comment by LukeHankey** [comment]
> > How do we want to handle the room owner leaving the game but client B still in the game? Do we:
> > Transfer ownership so the room now becomes Client B's room
> > Disconnect client B and send an error (HostLeftGame (?))
> 
> I prefer the first option since it allows for dropped connections etc. What do you think? When all the collaborators have left the room, **then** it should be deleted right?

Yes. That is currently what has been setup with room deletion. I also prefer the first option of transferring ownership.

**Comment by LukeHankey** [comment]
No time to do cursor movement.
