### ISSUE TITLE
Back-End

### ISSUE THREAD

**Issue by kappq** [Vthechamp22/kindly-kappa#4]
- [X] First layer - client connection and disconnection (#8)
  - [X] Create new sessions
  - [X] Handle rooms
- [x] Second layer - processing data
  - [x] Receive and process events, e.g. starting the game, moving the cursor in the text editor (#55 - partial)
  - [x] Broadcast processed events to all connected clients (in a room) (#36)
- [x] Third layer - introducing bugs
  - [x] Introduce random bugs inside the code (#7) (#29)
  - [x] Broadcast bugs to all connected clients (in a room) (#33 )

The tasks should be separated into smaller PRs. Any changes can be discussed below.

**Comment by LukeHankey** [comment]
Can you make these bullet points into a checklist so we can easily see what we have left to do? :)

**Comment by kappq** [comment]
> Can you make these bullet points into a checklist so we can easily see what we have left to do? :)

Done!
